// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCLI() {
  return window['go']['wails']['App']['CancelCLI']();
}

export function ClientPreferences() {
  return window['go']['wails']['App']['ClientPreferences']();
}

export function Diagnostics() {
  return window['go']['wails']['App']['Diagnostics']();
}

export function EditorAssociations() {
  return window['go']['wails']['App']['EditorAssociations']();
}

export function ExportTrafficReport() {
  return window['go']['wails']['App']['ExportTrafficReport']();
}

export function GitBranches() {
  return window['go']['wails']['App']['GitBranches']();
}

export function GitCheckout(arg1, arg2) {
  return window['go']['wails']['App']['GitCheckout'](arg1, arg2);
}

export function GitCommit(arg1, arg2, arg3) {
  return window['go']['wails']['App']['GitCommit'](arg1, arg2, arg3);
}

export function GitDiff(arg1) {
  return window['go']['wails']['App']['GitDiff'](arg1);
}

export function GitHistory(arg1) {
  return window['go']['wails']['App']['GitHistory'](arg1);
}

export function GitPull(arg1, arg2, arg3) {
  return window['go']['wails']['App']['GitPull'](arg1, arg2, arg3);
}

export function GitPush(arg1, arg2, arg3) {
  return window['go']['wails']['App']['GitPush'](arg1, arg2, arg3);
}

export function GitRemotes() {
  return window['go']['wails']['App']['GitRemotes']();
}

export function InspectStudioPlugin(arg1) {
  return window['go']['wails']['App']['InspectStudioPlugin'](arg1);
}

export function InstallStudioPlugin(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['App']['InstallStudioPlugin'](arg1, arg2, arg3, arg4);
}

export function InstalledStudioPluginManifests() {
  return window['go']['wails']['App']['InstalledStudioPluginManifests']();
}

export function InstalledStudioPlugins() {
  return window['go']['wails']['App']['InstalledStudioPlugins']();
}

export function ListProjects() {
  return window['go']['wails']['App']['ListProjects']();
}

export function OpenFileExternally(arg1, arg2) {
  return window['go']['wails']['App']['OpenFileExternally'](arg1, arg2);
}

export function OpenProject(arg1) {
  return window['go']['wails']['App']['OpenProject'](arg1);
}

export function PrepareRemoteHandoff(arg1) {
  return window['go']['wails']['App']['PrepareRemoteHandoff'](arg1);
}

export function ProductInfo() {
  return window['go']['wails']['App']['ProductInfo']();
}

export function ReadProjectFile(arg1) {
  return window['go']['wails']['App']['ReadProjectFile'](arg1);
}

export function ReadProjectSchema(arg1) {
  return window['go']['wails']['App']['ReadProjectSchema'](arg1);
}

export function ReadProjectSettings(arg1, arg2) {
  return window['go']['wails']['App']['ReadProjectSettings'](arg1, arg2);
}

export function ReadStudioPluginSurface(arg1, arg2, arg3) {
  return window['go']['wails']['App']['ReadStudioPluginSurface'](arg1, arg2, arg3);
}

export function ReadWorkspaceState() {
  return window['go']['wails']['App']['ReadWorkspaceState']();
}

export function RemoveStudioPlugin(arg1, arg2) {
  return window['go']['wails']['App']['RemoveStudioPlugin'](arg1, arg2);
}

export function RunCLI(arg1) {
  return window['go']['wails']['App']['RunCLI'](arg1);
}

export function RunStudioPluginTool(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['App']['RunStudioPluginTool'](arg1, arg2, arg3, arg4);
}

export function SaveClientPreferences(arg1) {
  return window['go']['wails']['App']['SaveClientPreferences'](arg1);
}

export function SaveEditorAssociation(arg1, arg2) {
  return window['go']['wails']['App']['SaveEditorAssociation'](arg1, arg2);
}

export function SelectExternalEditor() {
  return window['go']['wails']['App']['SelectExternalEditor']();
}

export function SelectProjectDirectory() {
  return window['go']['wails']['App']['SelectProjectDirectory']();
}

export function SelectStudioPluginPackage() {
  return window['go']['wails']['App']['SelectStudioPluginPackage']();
}

export function StartStudioPluginProcess(arg1, arg2) {
  return window['go']['wails']['App']['StartStudioPluginProcess'](arg1, arg2);
}

export function StopStudioPluginProcess(arg1, arg2) {
  return window['go']['wails']['App']['StopStudioPluginProcess'](arg1, arg2);
}

export function StudioPluginProcessStatus(arg1, arg2) {
  return window['go']['wails']['App']['StudioPluginProcessStatus'](arg1, arg2);
}

export function TrafficRecords() {
  return window['go']['wails']['App']['TrafficRecords']();
}

export function Workspace() {
  return window['go']['wails']['App']['Workspace']();
}

export function WriteProjectFile(arg1, arg2) {
  return window['go']['wails']['App']['WriteProjectFile'](arg1, arg2);
}

export function WriteProjectSettings(arg1, arg2, arg3) {
  return window['go']['wails']['App']['WriteProjectSettings'](arg1, arg2, arg3);
}

export function WriteWorkspaceState(arg1) {
  return window['go']['wails']['App']['WriteWorkspaceState'](arg1);
}
