// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import * as models from '../models';

export function CancelCLI():Promise<void>;

export function ClientPreferences():Promise<string>;

export function Diagnostics():Promise<Array<models.Diagnostic>>;

export function EditorAssociations():Promise<string>;

export function ExportTrafficReport():Promise<string>;

export function GitBranches():Promise<Array<models.GitBranch>>;

export function GitCheckout(arg1:string,arg2:boolean):Promise<void>;

export function GitCommit(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function GitDiff(arg1:string):Promise<models.GitDiff>;

export function GitHistory(arg1:number):Promise<Array<models.GitCommit>>;

export function GitPull(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitPush(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitRemotes():Promise<Array<models.GitRemote>>;

export function InspectStudioPlugin(arg1:string):Promise<string>;

export function InstallStudioPlugin(arg1:string,arg2:boolean,arg3:string,arg4:Array<string>):Promise<string>;

export function InstalledStudioPluginManifests():Promise<string>;

export function InstalledStudioPlugins():Promise<Array<models.InstalledPluginState>>;

export function ListProjects():Promise<Array<models.Project>>;

export function OpenFileExternally(arg1:string,arg2:string):Promise<void>;

export function OpenProject(arg1:string):Promise<models.Workspace>;

export function PrepareRemoteHandoff(arg1:string):Promise<string>;

export function ProductInfo():Promise<models.ProductInfo>;

export function ReadProjectFile(arg1:string):Promise<Array<number>>;

export function ReadProjectSchema(arg1:string):Promise<Array<number>>;

export function ReadProjectSettings(arg1:string,arg2:string):Promise<Array<number>>;

export function ReadStudioPluginSurface(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadWorkspaceState():Promise<models.WorkspaceState>;

export function RemoveStudioPlugin(arg1:string,arg2:string):Promise<void>;

export function RunCLI(arg1:Array<string>):Promise<void>;

export function RunStudioPluginTool(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function SaveClientPreferences(arg1:string):Promise<void>;

export function SaveEditorAssociation(arg1:string,arg2:string):Promise<void>;

export function SelectExternalEditor():Promise<string>;

export function SelectProjectDirectory():Promise<string>;

export function SelectStudioPluginPackage():Promise<string>;

export function StartStudioPluginProcess(arg1:string,arg2:string):Promise<string>;

export function StopStudioPluginProcess(arg1:string,arg2:string):Promise<void>;

export function StudioPluginProcessStatus(arg1:string,arg2:string):Promise<string>;

export function TrafficRecords():Promise<Array<models.TrafficRecordView>>;

export function Workspace():Promise<models.Workspace>;

export function WriteProjectFile(arg1:string,arg2:Array<number>):Promise<void>;

export function WriteProjectSettings(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function WriteWorkspaceState(arg1:models.WorkspaceState):Promise<void>;
